# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-deployment
  namespace: knative-serving
  labels:
    knative.dev/release: devel

data:
  # This is the Go import path for the binary that is containerized
  # and substituted here.
  queueSidecarImage: ko://knative.dev/serving/cmd/queue

  # Sets the queue proxy's CPU request.
  # If omitted, a default value (default "25m"), is used.
  queue-sidecar-cpu-request: "25m"

  # Sets the queue proxy's CPU limit.
  # If omitted, no value is specified and the system default is used.
  queue-sidecar-cpu-limit: "1000m"

  # Sets the queue proxy's memory request.
  # If omitted, no value is specified and the system default is used.
  queue-sidecar-memory-request: "50Mi"

  # Sets the queue proxy's memory limit.
  # If omitted, no value is specified and the system default is used.
  queue-sidecar-memory-limit: "800Mi"

  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # For examples of how to configure Knative components
    # consult their respective _example blocks:
    # - Serving: https://github.com/knative/serving/blob/master/config/core/configmaps/deployment.yaml#L24
