# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gc
  namespace: knative-serving
  labels:
    knative.dev/release: devel

data:
  # Since we don't run an activator, our minScale revisions don't
  # scale to zero when they become inactive, so instead we make
  # the GC settings fairly aggressive.
  # https://knative.dev/docs/serving/configuration/revision-gc/
  min-non-active-revisions: "0"
  # Only keep the last revision for rollbacks
  max-non-active-revisions: "1"
  retain-since-create-time: "disabled"
  # If a revision was active, then keep it around for this long
  # in case we need to rollback.
  retain-since-last-active-time: "12h"

  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # For examples of how to configure Knative components
    # consult their respective _example blocks:
    # - Serving: https://github.com/knative/serving/blob/master/config/core/configmaps/gc.yaml
