# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
  labels:
    knative.dev/release: devel

data:
  # The default networking integrations bundled with hakn.
  ingress.class: "istio.ingress.networking.knative.dev"

  # Gradually shift traffic over 30 seconds
  rollout-duration: "30s"

  # TODO: Enable auto-TLS based on self-signed certs.
  # autoTLS: "Enabled"
  # certificate.class: "net-http01.certificate.networking.knative.dev"

  # Create domain claims by default.
  autocreateClusterDomainClaims: "true"

  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # For examples of how to configure Knative components
    # consult their respective _example blocks:
    # - Serving: https://github.com/knative/serving/blob/master/config/core/configmaps/network.yaml
