# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  namespace: hakn-system
  labels:
    knative.dev/release: devel

data:
  # Leave a replica of each active revision available.
  min-scale: "1"

  # (with above) never have activator in the request path.
  target-burst-capacity: "0"

  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # For examples of how to configure Knative and Tekton components
    # consult their respective _example blocks:
    # - Serving: https://github.com/knative/serving/blob/master/config/core/configmaps/autoscaler.yaml
