# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-deployment
  namespace: hakn-system
  labels:
    knative.dev/release: devel

data:
  # This is the Go import path for the binary that is containerized
  # and substituted here.
  queueSidecarImage: ko://knative.dev/serving/cmd/queue

  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # For examples of how to configure Knative components
    # consult their respective _example blocks:
    # - Serving: https://github.com/knative/serving/blob/master/config/core/configmaps/deployment.yaml#L24
