# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-features
  namespace: hakn-system
  labels:
    knative.dev/release: devel
data:
  multi-container: enabled
  kubernetes.podspec-fieldref: enabled
  kubernetes.podspec-volumes-emptydir: enabled
  kubernetes.podspec-init-containers: enabled
  kubernetes.podspec-securitycontext: enabled

  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # For examples of how to configure Knative components
    # consult their respective _example blocks:
    # - Serving: https://github.com/knative/serving/blob/master/config/core/configmaps/features.yaml
