# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-addressable-resolver
  labels:
    knative.dev/release: devel
    duck.knative.dev/addressable: "true"

rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["serving.knative.dev"]
    resources: ["services", "services/status", "routes", "routes/status"]
    verbs: ["get", "list", "watch"]
