# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: controlplane
  namespace: hakn-system
  labels:
    knative.dev/release: devel

---
####################################################################
#
#  Cluster role binding to pull in all of the capabilities needed
#  by knative controllers and webhooks.
#
####################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-admin
  labels:
    knative.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: controlplane
    namespace: hakn-system
roleRef:
  kind: ClusterRole
  name: knative-role
  apiGroup: rbac.authorization.k8s.io

---
####################################################################
#
#  Cluster role binding to pull in all of the capabilities needed
#  by the net-istio controller.
#
####################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: net-istio-admin
  labels:
    knative.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: controlplane
    namespace: hakn-system
roleRef:
  kind: ClusterRole
  name: net-istio-role
  apiGroup: rbac.authorization.k8s.io

---
####################################################################
#
#  Aggregated cluster role and binding to pull in all capabilities
#  delegated to the knative serving controller.
#
####################################################################
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-serving-admin
  labels:
    knative.dev/release: devel
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      serving.knative.dev/controller: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-serving-controller-admin
  labels:
    knative.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: controlplane
    namespace: hakn-system
roleRef:
  kind: ClusterRole
  name: knative-serving-admin
  apiGroup: rbac.authorization.k8s.io

---
####################################################################
#
#  Aggregated cluster role and binding to pull in all of the
#  capabilities for addressable resolution.
#
####################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addressable-resolver
  labels:
    knative.dev/release: devel
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      duck.knative.dev/addressable: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hakn-addressable-resolver
  labels:
    knative.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: controlplane
    namespace: hakn-system
roleRef:
  kind: ClusterRole
  name: addressable-resolver
  apiGroup: rbac.authorization.k8s.io
